# 网站基本信息
title: "张小明 - 计算机科学与技术"
description: "计算机科学与技术专业学生的个人网站"
author: "张小明"
email: "your.email@example.com"

# GitHub 信息
github_username: yourusername
url: "https://yourusername.github.io"
baseurl: ""

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 社交媒体链接
social_links:
  github: yourusername
  linkedin: yourusername
  email: your.email@example.com

# SEO 设置
lang: zh-CN
timezone: Asia/Shanghai

# 网站图标
favicon: "/assets/favicon.ico"

# Google Analytics（可选）
# google_analytics: UA-XXXXXXXXX-X
